// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Register = 1,
  Opcode = 2,
  Program = 3,
  Assignment = 4,
  Identifier = 5,
  Equals = 6,
  Number = 7,
  OpenExpr = 8,
  CloseExpr = 9,
  Operator = 10,
  Comment = 11,
  Code = 12,
  Label = 13,
  Directive = 14,
  Immediate = 15,
  Comma = 16
